"use client"
import "./globals.css";
// import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator"
import BreadCrumb from "@/components/BreadCrumb";
import Sidebar from "@/components/Sidebar";
import Menu from "@/components/Menu";
import { useState } from "react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [dark, setDark] = useState(false);
  return (
    <html lang="en" className={dark? "dark": "light"}>
      <body className="flex flex-col h-dvh">
        <header className="w-full h-12">
          <Menu dark={dark} setDark={setDark} />
        </header>
        <Separator />
        <main className="flex flex-row h-lvh">
          <div className="w-[240px]">
            <Sidebar />
          </div>
          <Separator orientation="vertical"/>
          <div className="flex flex-col h-full w-full">
            <div className="w-full m-2">
              <BreadCrumb />
            </div>
            <div className="w-full h-full p-4">
              {children}
            </div>
          </div>
        </main>
        <Separator />
        <footer className="w-full h-12">
          footer
        </footer>
      </body>
    </html>
  );
}
