"use client"
import "./globals.css";
// import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator"
import BreadCrumb from "@/components/BreadCrumb";
import Sidebar from "@/components/Sidebar";
import Menu from "@/components/Menu";
// import { useState } from "react";
import useTheme from "@/hook/theme"


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [dark, setDark]: [boolean, (value: boolean) => void] = useState<boolean>(true);
  const darkTheme = useTheme(state => state.dark);
  return (
    <html lang="en" className={darkTheme? "dark": "light"}>
      <body className="flex flex-col w-screen h-screen">
        <header className="w-full h-12">
          <Menu />
        </header>
        <Separator />
        <main className="flex flex-row h-full">
          <div className="w-[240px]">
            <Sidebar />
          </div>
          <Separator orientation="vertical"/>
          <div className="h-full w-full">
            {/* <div className="w-full h-full"> */}
               {children}
            {/* </div>  */}
          </div>
        </main>
        <Separator />
        <footer className="w-full h-12">
          footer
        </footer>
      </body>
    </html>
  );
}
