export const people = [
    {
        id: 1,
        first_name: "Susanne",
        last_name: "Aldridge",
        email: "saldridge0@live.com",
        date_of_birth: "2009-06-22T09:37:12Z",
      },
      {
        id: 2,
        first_name: "Justis",
        last_name: "Dailly",
        email: "jdailly1@deviantart.com",
        date_of_birth: "1991-08-15T11:10:11Z",
      },
      {
        id: 3,
        first_name: "Shep",
        last_name: "MacConnulty",
        email: "smacconnulty2@desdev.cn",
        date_of_birth: "1966-03-06T17:27:17Z",
      },
      {
        id: 4,
        first_name: "Renelle",
        last_name: "Eunson",
        email: "reunson3@merriam-webster.com",
        date_of_birth: "1979-12-22T03:54:17Z",
      },
      {
        id: 5,
        first_name: "Pembroke",
        last_name: "Choke",
        email: "pchoke4@miibeian.gov.cn",
        date_of_birth: "1978-10-24T08:39:47Z",
      },
      {
        id: 6,
        first_name: "Raynard",
        last_name: "Simonutti",
        email: "rsimonutti5@dagondesign.com",
        date_of_birth: "2004-10-25T21:27:40Z",
      },
      {
        id: 7,
        first_name: "Elsinore",
        last_name: "Inchbald",
        email: "einchbald6@zimbio.com",
        date_of_birth: "2023-02-05T07:06:07Z",
      },
      {
        id: 8,
        first_name: "Ethelind",
        last_name: "Bryceson",
        email: "ebryceson7@wiley.com",
        date_of_birth: "2011-04-10T12:44:46Z",
      },
      {
        id: 9,
        first_name: "Windy",
        last_name: "Janaud",
        email: "wjanaud8@netscape.com",
        date_of_birth: "1983-07-28T07:18:23Z",
      },
      {
        id: 10,
        first_name: "Roberta",
        last_name: "Bedinn",
        email: "rbedinn9@prlog.org",
        date_of_birth: "2017-01-02T18:06:24Z",
      },
      {
        id: 11,
        first_name: "Illa",
        last_name: "McKeevers",
        email: "imckeeversa@archive.org",
        date_of_birth: "2005-09-22T03:21:35Z",
      },
      {
        id: 12,
        first_name: "Alvy",
        last_name: "Penburton",
        email: "apenburtonb@tripod.com",
        date_of_birth: "1951-07-16T23:16:34Z",
      },
      {
        id: 13,
        first_name: "Blake",
        last_name: "McNelis",
        email: "bmcnelisc@vimeo.com",
        date_of_birth: "2017-06-24T18:57:40Z",
      },
      {
        id: 14,
        first_name: "Roberto",
        last_name: "Dalmon",
        email: "rdalmond@nbcnews.com",
        date_of_birth: "1994-04-14T08:28:45Z",
      },
      {
        id: 15,
        first_name: "Rudolf",
        last_name: "Adamovitch",
        email: "radamovitche@msu.edu",
        date_of_birth: "1990-03-13T08:15:03Z",
      },
      {
        id: 16,
        first_name: "Antonius",
        last_name: "Langtry",
        email: "alangtryf@altervista.org",
        date_of_birth: "1975-06-23T04:32:58Z",
      },
      {
        id: 17,
        first_name: "Greggory",
        last_name: "Ragot",
        email: "gragotg@utexas.edu",
        date_of_birth: "2021-05-14T00:57:04Z",
      },
      {
        id: 18,
        first_name: "Rudolph",
        last_name: "Stearnes",
        email: "rstearnesh@soup.io",
        date_of_birth: "1980-09-27T13:51:43Z",
      },
      {
        id: 19,
        first_name: "Aubrie",
        last_name: "Winser",
        email: "awinseri@ovh.net",
        date_of_birth: "1985-05-24T15:12:21Z",
      },
      {
        id: 20,
        first_name: "Otho",
        last_name: "Village",
        email: "ovillagej@people.com.cn",
        date_of_birth: "1981-07-11T05:30:39Z",
      },
      {
        id: 21,
        first_name: "Elisabeth",
        last_name: "Mixhel",
        email: "emixhelk@theglobeandmail.com",
        date_of_birth: "1990-08-28T04:33:41Z",
      },
      {
        id: 22,
        first_name: "Haskel",
        last_name: "Risson",
        email: "hrissonl@skyrock.com",
        date_of_birth: "2020-11-06T09:26:34Z",
      },
      {
        id: 23,
        first_name: "Lizbeth",
        last_name: "Deinhard",
        email: "ldeinhardm@yahoo.com",
        date_of_birth: "1999-12-28T05:30:26Z",
      },
      {
        id: 24,
        first_name: "Rickie",
        last_name: "Goodyear",
        email: "rgoodyearn@ft.com",
        date_of_birth: "1964-07-13T12:21:06Z",
      },
      {
        id: 25,
        first_name: "Zorah",
        last_name: "Magowan",
        email: "zmagowano@scientificamerican.com",
        date_of_birth: "1968-10-12T10:21:48Z",
      },
      {
        id: 26,
        first_name: "Zora",
        last_name: "Megarry",
        email: "zmegarryp@lulu.com",
        date_of_birth: "1985-09-24T01:58:37Z",
      },
      {
        id: 27,
        first_name: "Perl",
        last_name: "Ferrar",
        email: "pferrarq@adobe.com",
        date_of_birth: "2023-04-14T01:48:58Z",
      },
      {
        id: 28,
        first_name: "Vanya",
        last_name: "Kleehuhler",
        email: "vkleehuhlerr@virginia.edu",
        date_of_birth: "2023-10-18T05:32:53Z",
      },
      {
        id: 29,
        first_name: "Vonnie",
        last_name: "Niset",
        email: "vnisets@cnbc.com",
        date_of_birth: "1977-05-18T21:31:31Z",
      },
      {
        id: 30,
        first_name: "Cathryn",
        last_name: "Barfoot",
        email: "cbarfoott@stanford.edu",
        date_of_birth: "1950-12-17T00:16:40Z",
      },
      {
        id: 31,
        first_name: "Waring",
        last_name: "Cavaney",
        email: "wcavaneyu@icq.com",
        date_of_birth: "1966-10-11T12:07:09Z",
      },
      {
        id: 32,
        first_name: "Trevor",
        last_name: "Ceccoli",
        email: "tceccoliv@amazon.co.uk",
        date_of_birth: "1986-01-11T22:28:19Z",
      },
      {
        id: 33,
        first_name: "Veronica",
        last_name: "Lipman",
        email: "vlipmanw@ebay.co.uk",
        date_of_birth: "2015-01-30T06:45:17Z",
      },
      {
        id: 34,
        first_name: "Gian",
        last_name: "Wilstead",
        email: "gwilsteadx@i2i.jp",
        date_of_birth: "2016-01-04T11:01:28Z",
      },
      {
        id: 35,
        first_name: "Lona",
        last_name: "Doerren",
        email: "ldoerreny@si.edu",
        date_of_birth: "2020-11-02T20:36:41Z",
      },
      {
        id: 36,
        first_name: "Worth",
        last_name: "Voas",
        email: "wvoasz@cornell.edu",
        date_of_birth: "1952-01-13T12:49:17Z",
      },
      {
        id: 37,
        first_name: "Kris",
        last_name: "McLise",
        email: "kmclise10@pcworld.com",
        date_of_birth: "2008-05-27T20:21:00Z",
      },
      {
        id: 38,
        first_name: "Emmie",
        last_name: "Piser",
        email: "episer11@indiegogo.com",
        date_of_birth: "2016-08-08T17:30:52Z",
      },
      {
        id: 39,
        first_name: "North",
        last_name: "Noorwood",
        email: "nnoorwood12@apple.com",
        date_of_birth: "2013-02-06T00:05:34Z",
      },
      {
        id: 40,
        first_name: "Britt",
        last_name: "De Paepe",
        email: "bdepaepe13@cdc.gov",
        date_of_birth: "1953-12-18T02:52:58Z",
      },
      {
        id: 41,
        first_name: "Marcus",
        last_name: "Perocci",
        email: "mperocci14@google.com",
        date_of_birth: "2005-05-13T11:52:17Z",
      },
      {
        id: 42,
        first_name: "Chris",
        last_name: "Legate",
        email: "clegate15@wufoo.com",
        date_of_birth: "1969-02-27T04:23:02Z",
      },
      {
        id: 43,
        first_name: "Dix",
        last_name: "Karys",
        email: "dkarys16@gravatar.com",
        date_of_birth: "1964-04-03T11:54:21Z",
      },
      {
        id: 44,
        first_name: "Sandor",
        last_name: "Gadesby",
        email: "sgadesby17@sciencedaily.com",
        date_of_birth: "1957-03-13T02:37:30Z",
      },
      {
        id: 45,
        first_name: "Rockie",
        last_name: "Eldritt",
        email: "reldritt18@mozilla.org",
        date_of_birth: "1964-12-10T12:57:49Z",
      },
      {
        id: 46,
        first_name: "Portie",
        last_name: "Cyseley",
        email: "pcyseley19@com.com",
        date_of_birth: "2013-12-11T10:47:49Z",
      },
      {
        id: 47,
        first_name: "Karlens",
        last_name: "Harrold",
        email: "kharrold1a@google.cn",
        date_of_birth: "1972-11-12T02:51:47Z",
      },
      {
        id: 48,
        first_name: "Kristin",
        last_name: "Burdfield",
        email: "kburdfield1b@cdbaby.com",
        date_of_birth: "2012-07-03T13:30:54Z",
      },
      {
        id: 49,
        first_name: "Hubie",
        last_name: "Benedicte",
        email: "hbenedicte1c@bandcamp.com",
        date_of_birth: "1987-03-09T00:54:12Z",
      },
      {
        id: 50,
        first_name: "Lura",
        last_name: "Brandrick",
        email: "lbrandrick1d@meetup.com",
        date_of_birth: "2023-01-20T20:57:23Z",
      },
      {
        id: 51,
        first_name: "Tobin",
        last_name: "Jagielski",
        email: "tjagielski1e@skyrock.com",
        date_of_birth: "2004-03-21T17:23:44Z",
      },
      {
        id: 52,
        first_name: "Amity",
        last_name: "Garford",
        email: "agarford1f@addtoany.com",
        date_of_birth: "2016-10-31T04:34:52Z",
      },
      {
        id: 53,
        first_name: "Amabel",
        last_name: "Tebbutt",
        email: "atebbutt1g@alibaba.com",
        date_of_birth: "1977-12-23T09:19:06Z",
      },
]
  
export type Person = (typeof people)[number]